/**
 * Object storage behind one interface so the provider is a configuration choice.
 *
 * Owns: the contract. Implementations: `LocalStorageAdapter` (disk, development only) and
 * `S3StorageAdapter` (any S3-compatible service: Supabase Storage, R2, S3, MinIO).
 */

import { type Readable } from 'node:stream';

/** Minimal object store. Keys are opaque, generated by the server, never user input. */
export interface StorageAdapter {
  /**
   * Writes an object, replacing any existing one with the same key.
   *
   * @param {string} key - Object key, for example `assets/<id>/<id>.png`.
   * @param {Buffer} body - File bytes.
   * @param {string} contentType - MIME type stored with the object.
   * @returns {Promise<void>} Resolves when the object is durable.
   */
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  /**
   * Opens an object for streaming.
   *
   * @param {string} key - Object key.
   * @returns {Promise<{ stream: Readable; contentLength: number | null }>} Readable stream
   *   and size when known.
   * @throws {AppError} `NOT_FOUND` when the key does not exist.
   */
  getStream(key: string): Promise<{ stream: Readable; contentLength: number | null }>;
  /**
   * Deletes an object; missing keys are not an error.
   *
   * @param {string} key - Object key.
   * @returns {Promise<void>} Resolves when gone.
   */
  delete(key: string): Promise<void>;
  /**
   * Checks whether the backend is reachable (readiness probe).
   *
   * @returns {Promise<boolean>} True when a trivial operation succeeded.
   */
  healthy(): Promise<boolean>;
}
